package server

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/irrigationreal/blob/internal/api"
)

func (s *Server) prepareFunctionBuild(ctx context.Context, src string, req *api.DeployRequest) error {
	if req.Build != "" {
		if err := s.runIn(ctx, src, "sh", "-c", req.Build); err != nil {
			return fmt.Errorf("build command %q: %w", req.Build, err)
		}
	}
	runtime := strings.ToLower(strings.TrimSpace(req.Runtime))
	if runtime == "" {
		runtime = "nodejs"
	}
	if runtime != "nodejs" && runtime != "node" {
		return fmt.Errorf("function runtime %q is not supported yet (use nodejs)", req.Runtime)
	}
	root, err := cleanFunctionPath(req.Root, ".")
	if err != nil {
		return fmt.Errorf("function root: %w", err)
	}
	rootPath := filepath.Join(src, filepath.FromSlash(root))
	if st, err := os.Stat(rootPath); err != nil || !st.IsDir() {
		return fmt.Errorf("function root %q does not exist after build", root)
	}
	handler, err := functionHandler(src, root, req.Handler)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(src, ".blob-function"), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(src, ".blob-function", "server.mjs"), []byte(functionRunnerJS), 0o644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(src, "Dockerfile.blob-function"), []byte(renderFunctionDockerfile(root, handler)), 0o644)
}

var functionHandlerCandidates = []string{
	"index.mjs", "index.js", "index.cjs",
	"function.mjs", "function.js", "function.cjs",
	"handler.mjs", "handler.js", "handler.cjs",
}

func functionHandler(src, root, configured string) (string, error) {
	if configured != "" {
		handler, err := cleanFunctionPath(configured, "")
		if err != nil {
			return "", fmt.Errorf("function handler: %w", err)
		}
		if err := validateFunctionHandlerPath(filepath.Join(src, filepath.FromSlash(root), filepath.FromSlash(handler))); err != nil {
			return "", fmt.Errorf("function handler %q under root %q: %w", handler, root, err)
		}
		return handler, nil
	}
	for _, candidate := range functionHandlerCandidates {
		if validateFunctionHandlerPath(filepath.Join(src, filepath.FromSlash(root), candidate)) == nil {
			return candidate, nil
		}
	}
	return "", fmt.Errorf("function handler not found under root %q; set handler: index.js or pass --handler", root)
}

func validateFunctionHandlerPath(path string) error {
	st, err := os.Lstat(path)
	if err != nil {
		return err
	}
	if !st.Mode().IsRegular() {
		return fmt.Errorf("not a regular file")
	}
	switch strings.ToLower(filepath.Ext(path)) {
	case ".js", ".mjs", ".cjs":
		return nil
	default:
		return fmt.Errorf("handler must be .js, .mjs, or .cjs")
	}
}

func cleanFunctionPath(path, def string) (string, error) {
	path = strings.TrimSpace(path)
	if path == "" {
		path = def
	}
	path = filepath.ToSlash(filepath.Clean(path))
	if path == "" || path == "." {
		return ".", nil
	}
	if strings.HasPrefix(path, "../") || path == ".." || strings.HasPrefix(path, "/") || strings.Contains(path, "\x00") {
		return "", fmt.Errorf("%q must stay inside the source tree", path)
	}
	return path, nil
}

func renderFunctionDockerfile(root, handler string) string {
	copySource := "."
	if root != "." {
		copySource = root + "/"
	}
	copySourceJSON, _ := json.Marshal([]string{copySource, "/srv/"})
	handlerJSON, _ := json.Marshal(handler)
	return fmt.Sprintf(`# generated by blobd
FROM node:22-alpine
WORKDIR /srv
COPY %s
RUN if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then npm ci --omit=dev; elif [ -f package.json ]; then npm install --omit=dev; fi
COPY .blob-function/server.mjs /blob-function/server.mjs
ENV NODE_ENV=production
ENV BLOB_FUNCTION_HANDLER=%s
EXPOSE 8080
CMD ["node","/blob-function/server.mjs"]
`, copySourceJSON, handlerJSON)
}

const functionRunnerJS = `import http from "node:http";
import { pathToFileURL } from "node:url";

const handlerPath = process.env.BLOB_FUNCTION_HANDLER || "index.js";
const mod = await import(pathToFileURL("/srv/" + handlerPath).href);
const handler = mod.default || mod.handler;

if (typeof handler !== "function") {
  throw new Error("Function module must export default or handler");
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on("data", chunk => chunks.push(chunk));
    req.on("end", () => resolve(Buffer.concat(chunks)));
    req.on("error", reject);
  });
}

function setHeaders(res, headers) {
  if (!headers) return;
  for (const [key, value] of Object.entries(headers)) {
    if (value !== undefined) res.setHeader(key, value);
  }
}

async function writeResult(res, result) {
  if (result === undefined) {
    res.statusCode = 204;
    res.end();
    return;
  }
  if (typeof Response !== "undefined" && result instanceof Response) {
    res.statusCode = result.status;
    result.headers.forEach((value, key) => res.setHeader(key, value));
    res.end(Buffer.from(await result.arrayBuffer()));
    return;
  }
  if (result && typeof result === "object" && ("statusCode" in result || "status" in result || "headers" in result || "body" in result)) {
    res.statusCode = result.statusCode || result.status || 200;
    setHeaders(res, result.headers);
    const body = result.body ?? "";
    if (Buffer.isBuffer(body) || typeof body === "string") {
      res.end(body);
    } else {
      if (!res.hasHeader("content-type")) res.setHeader("content-type", "application/json; charset=utf-8");
      res.end(JSON.stringify(body));
    }
    return;
  }
  if (Buffer.isBuffer(result) || typeof result === "string") {
    res.end(result);
    return;
  }
  res.setHeader("content-type", "application/json; charset=utf-8");
  res.end(JSON.stringify(result));
}

const server = http.createServer(async (req, res) => {
  try {
    const url = new URL(req.url, "http://blob-function.local");
    const body = await readBody(req);
    const event = {
      method: req.method,
      path: url.pathname,
      query: Object.fromEntries(url.searchParams.entries()),
      headers: req.headers,
      body: body.length ? body.toString("utf8") : null,
      rawBody: body.toString("base64"),
      isBase64Encoded: false,
    };
    await writeResult(res, await handler(event, { req }));
  } catch (err) {
    console.error(err && err.stack ? err.stack : err);
    res.statusCode = 500;
    res.setHeader("content-type", "application/json; charset=utf-8");
    res.end(JSON.stringify({ error: "function_error" }));
  }
});

server.listen(8080, "0.0.0.0", () => {
  console.log("blob function listening on :8080 handler=" + handlerPath);
});
`
