package server

import (
	"context"
	"fmt"
	stdlog "log"
	"os"
	"path/filepath"
	"strings"

	"github.com/darvell/blob/internal/api"
)

// prepareStaticBuild synthesizes a Dockerfile.blob-static and Caddyfile.blob
// inside the source tree so that the regular build path can build them.
//
// The image is a minimal caddy:2-alpine that serves /srv from `root` (the
// directory inside the user's source tree they chose to publish). For SPA
// sites we use try_files; for "extension-less URLs" (about.html under /about)
// we use the Caddy-native `try_files {path} {path}.html`.
func (s *Server) prepareStaticBuild(ctx context.Context, src string, req *api.DeployRequest) error {
	root := req.Root
	if root == "" {
		root = "."
	}
	if req.Build != "" {
		stdlog.Printf("static build: %s (cwd=%s)", req.Build, src)
		if err := s.runIn(ctx, src, "sh", "-c", req.Build); err != nil {
			return fmt.Errorf("build command %q: %w", req.Build, err)
		}
	}
	if req.Root == "" {
		for _, candidate := range []string{"dist", "build", "out", "_site", "public"} {
			if st, err := os.Stat(filepath.Join(src, candidate)); err == nil && st.IsDir() {
				root = candidate
				break
			}
		}
	}
	if _, err := os.Stat(filepath.Join(src, root)); err != nil {
		return fmt.Errorf("static root %q does not exist after build", root)
	}

	caddyfile := renderCaddyfile(root, req)
	dockerfile := renderStaticDockerfile(root)

	if err := os.WriteFile(filepath.Join(src, "Caddyfile.blob"), []byte(caddyfile), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(src, "Dockerfile.blob-static"), []byte(dockerfile), 0o644); err != nil {
		return err
	}
	return nil
}

func renderCaddyfile(root string, req *api.DeployRequest) string {
	index := req.Index
	if index == "" {
		index = "index.html"
	}
	notFound := req.NotFound
	var spaBlock string
	if req.SPA {
		spaBlock = "    try_files {path} /" + index + "\n"
	} else {
		spaBlock = "    try_files {path} {path}/ {path}.html\n"
	}
	notFoundBlock := ""
	if notFound != "" && !req.SPA {
		notFoundBlock = "\n    handle_errors {\n        @404 expression {err.status_code} == 404\n        rewrite @404 " + notFound + "\n        file_server\n    }"
	}
	return fmt.Sprintf(`:8080 {
    root * /srv
    encode zstd gzip
    file_server
%s%s
}
`, spaBlock, notFoundBlock)
}

func renderStaticDockerfile(root string) string {
	root = strings.TrimPrefix(root, "./")
	return fmt.Sprintf(`# generated by blobd
FROM caddy:2-alpine
WORKDIR /srv
COPY %s/ /srv/
COPY Caddyfile.blob /etc/caddy/Caddyfile
EXPOSE 8080
CMD ["caddy","run","--config","/etc/caddy/Caddyfile","--adapter","caddyfile"]
`, root)
}
